name: Security Vulnerability
description: Report a security vulnerability (for non-critical issues only)
title: "[Security]: "
labels: ["security", "priority-high"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Important Security Notice

        **For critical security vulnerabilities**, please DO NOT use this public issue tracker.
        Instead, please report them privately via email to: security@nexops.local

        This template is for non-critical security issues that can be discussed publicly.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Low - Minor security concern
        - Medium - Could be exploited under specific conditions
        - High - Significant security risk (consider private disclosure)
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Input Validation
        - Information Disclosure
        - Dependency Vulnerability
        - Configuration Issue
        - RBAC/Permissions
        - API Security
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue
      placeholder: A clear description of the vulnerability...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker do with this vulnerability?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be demonstrated?
      placeholder: |
        1. Configure NextSight with...
        2. Send request to...
        3. Observe...

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have any suggestions for fixing this issue?

  - type: textarea
    id: affected
    attributes:
      label: Affected Versions
      description: Which versions of NextSight are affected?
      placeholder: "e.g., 1.0.0 - 1.3.0"

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: This is NOT a critical vulnerability that requires private disclosure
          required: true
        - label: I have not exploited this vulnerability maliciously
          required: true
