"""Add pipeline, incident, and timeline tables

Revision ID: 078b9fb1e2f9
Revises: 001_initial
Create Date: 2025-12-10 15:08:26.552669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078b9fb1e2f9'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='incidentseverity'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'IDENTIFIED', 'MONITORING', 'RESOLVED', name='incidentstatus'), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('affected_services', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('yaml_template', sa.Text(), nullable=False),
    sa.Column('default_stages', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_templates_category', 'pipeline_templates', ['category'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository', sa.String(length=500), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.Enum('GITHUB', 'GITLAB', 'BITBUCKET', 'MANUAL', name='provider'), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('yaml_config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('successful_runs', sa.Integer(), nullable=True),
    sa.Column('failed_runs', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('last_run_id', sa.String(length=36), nullable=True),
    sa.Column('last_run_status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='pipelinestatus'), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_duration', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipelines_is_active', 'pipelines', ['is_active'], unique=False)
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=False)
    op.create_index('ix_pipelines_name_provider', 'pipelines', ['name', 'provider'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('DEPLOYMENT', 'CONFIG_CHANGE', 'SCALE_EVENT', 'BUILD', 'INCIDENT', 'ROLLBACK', 'FEATURE_FLAG', 'INFRASTRUCTURE', name='changetype'), nullable=False),
    sa.Column('source', sa.Enum('KUBERNETES', 'JENKINS', 'MANUAL', 'GITHUB', 'TERRAFORM', name='changesource'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('related_incident_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='pipelinestatus'), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'PUSH', 'PULL_REQUEST', 'TAG', 'SCHEDULE', 'WEBHOOK', name='triggertype'), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_runs_pipeline_id', 'pipeline_runs', ['pipeline_id'], unique=False)
    op.create_index('ix_pipeline_runs_started_at', 'pipeline_runs', ['started_at'], unique=False)
    op.create_index('ix_pipeline_runs_status', 'pipeline_runs', ['status'], unique=False)
    op.create_table('pipeline_secrets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_secrets_pipeline_id', 'pipeline_secrets', ['pipeline_id'], unique=False)
    op.create_table('pipeline_triggers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'PUSH', 'PULL_REQUEST', 'TAG', 'SCHEDULE', 'WEBHOOK', name='triggertype'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('branches', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('paths', sa.JSON(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('webhook_secret', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_triggers_pipeline_id', 'pipeline_triggers', ['pipeline_id'], unique=False)
    op.create_table('pipeline_variables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_variables_name', 'pipeline_variables', ['name'], unique=False)
    op.create_index('ix_pipeline_variables_pipeline_id', 'pipeline_variables', ['pipeline_id'], unique=False)
    op.create_table('pipeline_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_logs_run_id', 'pipeline_logs', ['run_id'], unique=False)
    op.create_index('ix_pipeline_logs_timestamp', 'pipeline_logs', ['timestamp'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', name='stagestatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_stages_run_id', 'pipeline_stages', ['run_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp_desc', 'audit_logs', [sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_timestamp_desc', table_name='audit_logs')
    op.drop_index('ix_pipeline_stages_run_id', table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index('ix_pipeline_logs_timestamp', table_name='pipeline_logs')
    op.drop_index('ix_pipeline_logs_run_id', table_name='pipeline_logs')
    op.drop_table('pipeline_logs')
    op.drop_index('ix_pipeline_variables_pipeline_id', table_name='pipeline_variables')
    op.drop_index('ix_pipeline_variables_name', table_name='pipeline_variables')
    op.drop_table('pipeline_variables')
    op.drop_index('ix_pipeline_triggers_pipeline_id', table_name='pipeline_triggers')
    op.drop_table('pipeline_triggers')
    op.drop_index('ix_pipeline_secrets_pipeline_id', table_name='pipeline_secrets')
    op.drop_table('pipeline_secrets')
    op.drop_index('ix_pipeline_runs_status', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_started_at', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_pipeline_id', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('timeline_events')
    op.drop_index('ix_pipelines_name_provider', table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.drop_index('ix_pipelines_is_active', table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index('ix_pipeline_templates_category', table_name='pipeline_templates')
    op.drop_table('pipeline_templates')
    op.drop_table('incidents')
    # ### end Alembic commands ###
