"""Add user_permissions table and use_custom_permissions flag

Revision ID: 38db47245c05
Revises: 8dfcaf130a4a
Create Date: 2025-12-14 21:37:56.414288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38db47245c05'
down_revision: Union[str, None] = '8dfcaf130a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: user_permissions table already exists from a previous partial migration
    # Only adding the missing column to users table

    # Add use_custom_permissions column to users table
    op.add_column('users', sa.Column('use_custom_permissions', sa.Boolean(), nullable=False, server_default='false'))

    # The user_permissions table already exists, but ensure indexes and constraints exist
    # These will silently fail if they already exist (using IF NOT EXISTS semantics via raw SQL)
    conn = op.get_bind()

    # Add foreign key if missing
    try:
        conn.execute(sa.text('''
            ALTER TABLE user_permissions
            ADD CONSTRAINT user_permissions_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        '''))
    except Exception:
        pass  # FK might already exist

    # Add unique constraint if missing
    try:
        conn.execute(sa.text('''
            ALTER TABLE user_permissions
            ADD CONSTRAINT uq_user_permission UNIQUE (user_id, permission)
        '''))
    except Exception:
        pass  # Constraint might already exist

    # Create indexes if not exists
    try:
        conn.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_user_permissions_user ON user_permissions (user_id)'))
    except Exception:
        pass

    try:
        conn.execute(sa.text('CREATE INDEX IF NOT EXISTS ix_user_permissions_category ON user_permissions (category)'))
    except Exception:
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop user_permissions table
    op.drop_constraint('uq_user_permission', 'user_permissions', type_='unique')
    op.drop_index('ix_user_permissions_category', 'user_permissions')
    op.drop_index('ix_user_permissions_user', 'user_permissions')
    op.drop_table('user_permissions')

    # Drop enum type
    op.execute('DROP TYPE IF EXISTS permissioncategory')

    # Remove column from users table
    op.drop_column('users', 'use_custom_permissions')

    # ### end Alembic commands ###
