"""Add pipeline approval system

Revision ID: 8dfcaf130a4a
Revises: 006_managed_integration
Create Date: 2025-12-12 16:56:10.491930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dfcaf130a4a'
down_revision: Union[str, None] = '006_managed_integration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_tokens_hash', table_name='api_tokens')
    op.drop_index('ix_api_tokens_user_id', table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index('ix_integrations_name', table_name='integrations')
    op.drop_table('integrations')
    op.drop_index('ix_user_settings_user_id', table_name='user_settings')
    op.drop_table('user_settings')
    op.alter_column('agent_job_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('coverage_trends', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('coverage_trends', 'branch',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'main'::character varying"))
    op.alter_column('pipeline_agents', 'port',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('8080'))
    op.alter_column('pipeline_agents', 'status',
               existing_type=postgresql.ENUM('online', 'offline', 'busy', 'maintenance', name='agentstatus'),
               nullable=True,
               existing_server_default=sa.text("'offline'::agentstatus"))
    op.alter_column('pipeline_agents', 'labels',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('pipeline_agents', 'max_concurrent_jobs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('pipeline_agents', 'current_jobs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_agents', 'workspace_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("'/tmp/nexops-agent'::character varying"))
    op.alter_column('pipeline_agents', 'docker_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pipeline_agents', 'kubernetes_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pipeline_agents', 'pool',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('pipeline_agents', 'total_jobs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_agents', 'successful_jobs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_agents', 'failed_jobs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_agents', 'avg_job_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('pipeline_coverage', sa.Column('uncovered_lines_summary', sa.JSON(), nullable=True))
    op.alter_column('pipeline_coverage', 'file_coverage',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('pipeline_coverage', 'lowest_coverage_files',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.add_column('pipeline_stages', sa.Column('requires_approval', sa.Boolean(), nullable=True))
    op.add_column('pipeline_stages', sa.Column('approval_type', sa.String(length=50), nullable=True))
    op.add_column('pipeline_stages', sa.Column('required_approvers', sa.Integer(), nullable=True))
    op.add_column('pipeline_stages', sa.Column('approver_roles', sa.JSON(), nullable=True))
    op.alter_column('pipeline_test_results', 'framework',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'other'::character varying"))
    op.alter_column('pipeline_test_results', 'total_tests',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_test_results', 'passed_tests',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_test_results', 'failed_tests',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_test_results', 'skipped_tests',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_test_results', 'error_tests',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_test_results', 'pass_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('pipeline_test_results', 'test_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('pipeline_test_results', 'failed_test_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_pipeline_test_results_framework', table_name='pipeline_test_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pipeline_test_results_framework', 'pipeline_test_results', ['framework'], unique=False)
    op.alter_column('pipeline_test_results', 'failed_test_names',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('pipeline_test_results', 'test_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('pipeline_test_results', 'pass_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('pipeline_test_results', 'error_tests',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_test_results', 'skipped_tests',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_test_results', 'failed_tests',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_test_results', 'passed_tests',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_test_results', 'total_tests',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_test_results', 'framework',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'other'::character varying"))
    op.drop_column('pipeline_stages', 'approver_roles')
    op.drop_column('pipeline_stages', 'required_approvers')
    op.drop_column('pipeline_stages', 'approval_type')
    op.drop_column('pipeline_stages', 'requires_approval')
    op.alter_column('pipeline_coverage', 'lowest_coverage_files',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('pipeline_coverage', 'file_coverage',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('pipeline_coverage', 'uncovered_lines_summary')
    op.alter_column('pipeline_agents', 'avg_job_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_agents', 'failed_jobs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_agents', 'successful_jobs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_agents', 'total_jobs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_agents', 'pool',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('pipeline_agents', 'kubernetes_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('pipeline_agents', 'docker_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('pipeline_agents', 'workspace_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("'/tmp/nexops-agent'::character varying"))
    op.alter_column('pipeline_agents', 'current_jobs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_agents', 'max_concurrent_jobs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('pipeline_agents', 'labels',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('pipeline_agents', 'status',
               existing_type=postgresql.ENUM('online', 'offline', 'busy', 'maintenance', name='agentstatus'),
               nullable=False,
               existing_server_default=sa.text("'offline'::agentstatus"))
    op.alter_column('pipeline_agents', 'port',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('8080'))
    op.alter_column('coverage_trends', 'branch',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'main'::character varying"))
    op.alter_column('coverage_trends', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_job_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('user_settings',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=20), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('default_namespace', sa.VARCHAR(length=100), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.Column('auto_refresh', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('refresh_interval_seconds', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=False),
    sa.Column('date_format', sa.VARCHAR(length=20), server_default=sa.text("'YYYY-MM-DD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_settings_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_settings_pkey'),
    sa.UniqueConstraint('user_id', name='user_settings_user_id_key')
    )
    op.create_index('ix_user_settings_user_id', 'user_settings', ['user_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('source-control', 'ci-cd', 'monitoring', 'logging', 'cloud', 'notification', name='integrationcategory'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('connected', 'disconnected', 'error', name='integrationstatus'), server_default=sa.text("'disconnected'::integrationstatus"), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('auto_sync', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('sync_interval_seconds', sa.INTEGER(), server_default=sa.text('300'), autoincrement=False, nullable=False),
    sa.Column('last_sync', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('health_check_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_managed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('setup_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='integrations_pkey')
    )
    op.create_index('ix_integrations_name', 'integrations', ['name'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_used', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='api_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='api_tokens_pkey')
    )
    op.create_index('ix_api_tokens_user_id', 'api_tokens', ['user_id'], unique=False)
    op.create_index('ix_api_tokens_hash', 'api_tokens', ['token_hash'], unique=False)
    # ### end Alembic commands ###
